"""Directed stormwater drainage graph layer for Chennai flood nowcasting.

This module turns ward-level GCC/OpenCity KML drain lines into a projected
``networkx.DiGraph`` that can be coupled later to DEM and rainfall grids.

Hydraulic assumption note for judges
------------------------------------
CPHEEO's *Manual on Storm Water Drainage Systems, Volume I - Engineering
Design* (MoHUA, 2019) frames storm-drain hydraulic checks around surveyed
geometry, slopes and Manning's equation. Public KML coverage usually lacks
pipe/open-channel dimensions, so the defaults below are deliberately labelled
proxy assumptions: hierarchy-specific rectangular channel dimensions, a
concrete-lined Manning roughness, and a mild bed slope. Replace
``DEFAULT_CAPACITY_ASSUMPTIONS`` or pass measured edge attributes when survey
data becomes available; the public API stays the same.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from enum import Enum
from math import hypot, pi, sqrt
from numbers import Integral
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Sequence

import networkx as nx
from pyproj import Transformer
from shapely.geometry import GeometryCollection, LineString, MultiLineString
from shapely.ops import unary_union
from shapely.strtree import STRtree

DEFAULT_SOURCE_CRS = "EPSG:4326"
DEFAULT_TARGET_CRS = "EPSG:32644"


class SurchargeStatus(str, Enum):
    """Capacity state used by the later 2D surface-flow coupling layer."""

    NORMAL = "normal"
    WATCH = "watch"
    SURCHARGING = "surcharging"


@dataclass(frozen=True)
class CapacityAssumption:
    """Proxy hydraulic parameters for drains whose survey dimensions are absent."""

    hierarchy: str
    width_m: float
    depth_m: float
    manning_n: float
    slope: float


@dataclass
class NodeState:
    inflow_volume_m3: float = 0.0
    outgoing_capacity_volume_m3: float = 0.0
    capacity_utilization: float = 0.0
    surcharging: SurchargeStatus = SurchargeStatus.NORMAL


@dataclass
class EdgeState:
    flow_m3s: float = 0.0
    volume_m3: float = 0.0
    capacity_utilization: float = 0.0
    surcharging: SurchargeStatus = SurchargeStatus.NORMAL


DEFAULT_CAPACITY_ASSUMPTIONS: dict[str, CapacityAssumption] = {
    "primary": CapacityAssumption(
        hierarchy="primary", width_m=2.4, depth_m=1.8, manning_n=0.015, slope=0.0010
    ),
    "secondary": CapacityAssumption(
        hierarchy="secondary", width_m=1.2, depth_m=1.0, manning_n=0.015, slope=0.0012
    ),
    "tertiary": CapacityAssumption(
        hierarchy="tertiary", width_m=0.6, depth_m=0.6, manning_n=0.015, slope=0.0015
    ),
}

AttributeDict = dict[str, Any]
DemSampler = Callable[[float, float], float | None]


def load_drainage_graph(
    kml_path: str | Path | Sequence[str | Path],
    *,
    target_crs: str = DEFAULT_TARGET_CRS,
    dem_sampler: DemSampler | None = None,
    dem_transform: Any | None = None,
    dem_shape: tuple[int, int] | None = None,
    outfall_points: Sequence[tuple[float, float]] | None = None,
    node_precision_m: float = 0.5,
    snap_tolerance_m: float = 1.0,
    min_segment_length_m: float = 0.25,
    direction_fallback: str = "east",
    capacity_assumptions: Mapping[str, CapacityAssumption] | None = None,
) -> nx.DiGraph:
    """Load one or more drain KML/KMZ files into a directed drainage graph.

    Args:
        kml_path: KML/KMZ file, directory, or sequence of files/directories.
        target_crs: Projected CRS for graph coordinates. EPSG:32644 is Chennai's
            WGS84 UTM zone and aligns distances/capacities in metres.
        dem_sampler: Optional callable receiving projected ``(x, y)`` and
            returning elevation in metres. If supplied, edges are directed
            downhill.
        dem_transform: Optional DEM affine/GDAL geotransform used to add
            ``dem_row`` and ``dem_col`` to each node.
        dem_shape: Optional ``(rows, cols)`` bounds for DEM index clipping.
        outfall_points: Optional projected or lon/lat points. When no DEM slope
            is available, segments are directed toward the nearest outfall.
        node_precision_m: Endpoint snapping precision in projected metres.
        snap_tolerance_m: Tolerance for assigning noded segments back to source
            KML attributes.
        min_segment_length_m: Drop tiny slivers generated by geometric noding.
        direction_fallback: Deterministic fallback if DEM/outfalls are absent:
            ``east`` is suitable as a weak Chennai coastward prior.
        capacity_assumptions: Override hierarchy capacity assumptions.

    Returns:
        A ``networkx.DiGraph`` with projected node coordinates and hydraulic
        attributes on each edge.
    """

    assumptions = dict(capacity_assumptions or DEFAULT_CAPACITY_ASSUMPTIONS)
    raw_lines = _read_drain_lines(kml_path, target_crs)
    graph = nx.DiGraph(
        crs=target_crs,
        source_crs=DEFAULT_SOURCE_CRS,
        node_precision_m=node_precision_m,
        capacity_assumptions={k: asdict(v) for k, v in assumptions.items()},
    )
    if not raw_lines:
        return graph

    source_geometries = [item["geometry"] for item in raw_lines]
    tree = STRtree(source_geometries)
    source_id_to_index = {id(geometry): index for index, geometry in enumerate(source_geometries)}
    noded_segments = _line_parts(unary_union(source_geometries))
    node_ids_by_key: dict[tuple[int, int], str] = {}
    to_lonlat = Transformer.from_crs(target_crs, DEFAULT_SOURCE_CRS, always_xy=True)
    projected_outfalls = _project_outfalls(outfall_points, target_crs)

    for segment in noded_segments:
        if segment.length < min_segment_length_m:
            continue
        source = _nearest_source_line(
            segment, raw_lines, tree, source_id_to_index, snap_tolerance_m
        )
        attributes = dict(source["attributes"]) if source else {}
        hierarchy = _infer_hierarchy(attributes)
        direction = _direct_segment(
            segment=segment,
            attributes=attributes,
            dem_sampler=dem_sampler,
            outfall_points=projected_outfalls,
            direction_fallback=direction_fallback,
        )
        coords = direction["coords"]
        start_key = _node_key(coords[0], node_precision_m)
        end_key = _node_key(coords[-1], node_precision_m)
        start_id = _ensure_node(graph, node_ids_by_key, start_key, coords[0], to_lonlat, dem_transform, dem_shape)
        end_id = _ensure_node(graph, node_ids_by_key, end_key, coords[-1], to_lonlat, dem_transform, dem_shape)
        edge_attrs = _edge_attributes(
            segment=LineString(coords),
            source_attributes=attributes,
            hierarchy=hierarchy,
            direction=direction,
            assumptions=assumptions,
        )
        _add_or_merge_edge(graph, start_id, end_id, edge_attrs)

    _classify_node_kinds(graph)
    initialize_graph_state(graph)
    return graph


def estimate_capacity(
    edge: Mapping[str, Any],
    assumptions: Mapping[str, CapacityAssumption] | None = None,
) -> float:
    """Estimate full-flow hydraulic capacity in m³/s using Manning's equation.

    If edge attributes include measured ``diameter_m``/``diameter_mm`` this uses
    a circular full-flow section. Otherwise it uses measured ``width_m`` and
    ``depth_m`` when present, falling back to hierarchy proxies. These proxies
    are CPHEEO-style design placeholders, not a substitute for surveyed
    cross-sections.
    """

    capacity = _parse_float(_lookup(edge, ("capacity_m3s", "capacity", "q_capacity")))
    if capacity is not None:
        return capacity

    active_assumptions = assumptions or DEFAULT_CAPACITY_ASSUMPTIONS
    hierarchy = _infer_hierarchy(edge)
    assumption = active_assumptions.get(hierarchy, active_assumptions["secondary"])
    slope = _positive_float(
        _parse_float(_lookup(edge, ("slope", "bed_slope", "gradient"))), assumption.slope
    )
    manning_n = _positive_float(
        _parse_float(_lookup(edge, ("manning_n", "n", "roughness"))), assumption.manning_n
    )
    diameter_m = _diameter_metres(edge)
    if diameter_m is not None:
        radius = diameter_m / 2.0
        area = pi * radius * radius
        wetted_perimeter = 2.0 * pi * radius
    else:
        width = _positive_float(
            _parse_float(_lookup(edge, ("width_m", "width", "drain_width", "top_width"))),
            assumption.width_m,
        )
        depth = _positive_float(
            _parse_float(_lookup(edge, ("depth_m", "depth", "drain_depth", "height"))),
            assumption.depth_m,
        )
        area = width * depth
        wetted_perimeter = width + (2.0 * depth)

    hydraulic_radius = area / wetted_perimeter
    return (1.0 / manning_n) * area * (hydraulic_radius ** (2.0 / 3.0)) * sqrt(slope)


def initialize_graph_state(graph: nx.DiGraph) -> None:
    """Attach zeroed node and edge state dictionaries in-place."""

    for node_id in graph.nodes:
        state = asdict(NodeState())
        state["surcharging"] = SurchargeStatus.NORMAL.value
        graph.nodes[node_id]["state"] = state
    for _, _, attrs in graph.edges(data=True):
        state = asdict(EdgeState())
        state["surcharging"] = SurchargeStatus.NORMAL.value
        attrs["state"] = state


def update_node_state(
    graph: nx.DiGraph,
    node: str,
    inflow_volume_m3: float,
    dt_seconds: float,
) -> dict[str, Any]:
    """Update one node's inflow/utilization/surcharging state for a timestep."""

    if dt_seconds <= 0:
        raise ValueError("dt_seconds must be positive")
    outgoing_capacity_m3s = sum(
        attrs.get("capacity_m3s", 0.0) for _, _, attrs in graph.out_edges(node, data=True)
    )
    outgoing_capacity_volume = outgoing_capacity_m3s * dt_seconds
    utilization = (
        inflow_volume_m3 / outgoing_capacity_volume if outgoing_capacity_volume > 0.0 else float("inf")
    )
    state = NodeState(
        inflow_volume_m3=float(inflow_volume_m3),
        outgoing_capacity_volume_m3=outgoing_capacity_volume,
        capacity_utilization=utilization,
        surcharging=_status_from_utilization(utilization),
    )
    graph.nodes[node]["state"] = asdict(state)
    graph.nodes[node]["state"]["surcharging"] = state.surcharging.value
    return graph.nodes[node]["state"]


def update_edge_state(
    graph: nx.DiGraph,
    u: str,
    v: str,
    *,
    flow_m3s: float | None = None,
    volume_m3: float | None = None,
    dt_seconds: float = 60.0,
) -> dict[str, Any]:
    """Update one directed edge's flow/utilization/surcharging state."""

    if dt_seconds <= 0:
        raise ValueError("dt_seconds must be positive")
    if flow_m3s is None and volume_m3 is None:
        raise ValueError("provide flow_m3s or volume_m3")
    if flow_m3s is None:
        flow_m3s = float(volume_m3 or 0.0) / dt_seconds
    if volume_m3 is None:
        volume_m3 = float(flow_m3s) * dt_seconds

    attrs = graph.edges[u, v]
    capacity = attrs.get("capacity_m3s", 0.0)
    utilization = float(flow_m3s) / capacity if capacity > 0.0 else float("inf")
    state = EdgeState(
        flow_m3s=float(flow_m3s),
        volume_m3=float(volume_m3),
        capacity_utilization=utilization,
        surcharging=_status_from_utilization(utilization),
    )
    attrs["state"] = asdict(state)
    attrs["state"]["surcharging"] = state.surcharging.value
    return attrs["state"]


def update_graph_state(
    graph: nx.DiGraph,
    *,
    node_inflows_m3: Mapping[str, float] | None = None,
    edge_flows_m3s: Mapping[tuple[str, str], float] | None = None,
    dt_seconds: float = 60.0,
) -> None:
    """Batch-update node and edge states for a simulation timestep."""

    for node, inflow in (node_inflows_m3 or {}).items():
        update_node_state(graph, node, inflow, dt_seconds)
    for edge, flow in (edge_flows_m3s or {}).items():
        update_edge_state(graph, edge[0], edge[1], flow_m3s=flow, dt_seconds=dt_seconds)


def snap_point_to_dem_grid(
    x: float,
    y: float,
    dem_transform: Any,
    dem_shape: tuple[int, int] | None = None,
) -> tuple[int, int] | None:
    """Return ``(row, col)`` of the DEM cell nearest a projected graph point.

    ``dem_transform`` may be a rasterio/affine transform or a GDAL geotransform
    tuple ``(origin_x, pixel_width, x_skew, origin_y, y_skew, pixel_height)``.
    """

    if hasattr(dem_transform, "__invert__"):
        col_float, row_float = (~dem_transform) * (x, y)
    else:
        origin_x, pixel_width, x_skew, origin_y, y_skew, pixel_height = dem_transform
        if x_skew != 0 or y_skew != 0:
            raise ValueError("skewed GDAL geotransforms require an affine transform object")
        col_float = (x - origin_x) / pixel_width
        row_float = (y - origin_y) / pixel_height

    row = int(round(row_float))
    col = int(round(col_float))
    if dem_shape is not None:
        rows, cols = dem_shape
        if row < 0 or col < 0 or row >= rows or col >= cols:
            return None
    return row, col


def plot_graph_state(
    graph: nx.DiGraph,
    *,
    ax: Any | None = None,
    node_size: float = 12.0,
    edge_width: float = 1.8,
    cmap: str = "viridis",
) -> Any:
    """Plot graph nodes/edges coloured by capacity utilization for debugging."""

    import matplotlib.pyplot as plt
    from matplotlib.collections import LineCollection

    if ax is None:
        _, ax = plt.subplots(figsize=(8, 8))

    segments = []
    edge_utilization = []
    for _, _, attrs in graph.edges(data=True):
        geometry = attrs.get("geometry")
        if geometry is None:
            continue
        segments.append(list(geometry.coords))
        edge_utilization.append(_state_utilization(attrs))

    if segments:
        collection = LineCollection(
            segments,
            array=edge_utilization,
            cmap=cmap,
            linewidths=edge_width,
        )
        ax.add_collection(collection)
        plt.colorbar(collection, ax=ax, label="edge capacity utilization")

    xs = [attrs["x"] for _, attrs in graph.nodes(data=True)]
    ys = [attrs["y"] for _, attrs in graph.nodes(data=True)]
    node_utilization = [_state_utilization(attrs) for _, attrs in graph.nodes(data=True)]
    if xs:
        ax.scatter(xs, ys, c=node_utilization, cmap=cmap, s=node_size, edgecolors="none")

    ax.set_aspect("equal", adjustable="datalim")
    ax.set_title("Stormwater drainage graph state")
    ax.set_xlabel(f"x ({graph.graph.get('crs', DEFAULT_TARGET_CRS)})")
    ax.set_ylabel(f"y ({graph.graph.get('crs', DEFAULT_TARGET_CRS)})")
    return ax


def _read_drain_lines(kml_path: str | Path | Sequence[str | Path], target_crs: str) -> list[AttributeDict]:
    import fiona
    import geopandas as gpd

    for driver in ("KML", "LIBKML"):
        fiona.drvsupport.supported_drivers[driver] = "rw"

    drain_lines: list[AttributeDict] = []
    for path in _expand_paths(kml_path):
        layers = _layers_for_path(path, fiona)
        for layer in layers:
            try:
                frame = gpd.read_file(path, layer=layer)
            except Exception:
                frame = gpd.read_file(path, driver="KML", layer=layer)
            if frame.empty:
                continue
            if frame.crs is None:
                frame = frame.set_crs(DEFAULT_SOURCE_CRS, allow_override=True)
            frame = frame.to_crs(target_crs)
            for _, row in frame.iterrows():
                attributes = {
                    str(key): value
                    for key, value in row.drop(labels="geometry").to_dict().items()
                    if value is not None and str(value).lower() != "nan"
                }
                attributes["source_file"] = str(path)
                attributes["source_layer"] = str(layer)
                for line in _line_parts(row.geometry):
                    if not line.is_empty and line.length > 0:
                        drain_lines.append({"geometry": line, "attributes": attributes})
    return drain_lines


def _expand_paths(kml_path: str | Path | Sequence[str | Path]) -> list[Path]:
    raw_paths: Iterable[str | Path]
    if isinstance(kml_path, (str, Path)):
        raw_paths = (kml_path,)
    else:
        raw_paths = kml_path

    paths: list[Path] = []
    for raw_path in raw_paths:
        path = Path(raw_path)
        if path.is_dir():
            paths.extend(sorted(path.glob("*.kml")))
            paths.extend(sorted(path.glob("*.kmz")))
        else:
            paths.append(path)
    missing = [str(path) for path in paths if not path.exists()]
    if missing:
        raise FileNotFoundError(f"KML path(s) not found: {', '.join(missing)}")
    return paths


def _layers_for_path(path: Path, fiona: Any) -> list[str | None]:
    try:
        layers = list(fiona.listlayers(path))
    except Exception:
        return [None]
    return layers or [None]


def _line_parts(geometry: Any) -> list[LineString]:
    if geometry is None or geometry.is_empty:
        return []
    if isinstance(geometry, LineString):
        return [geometry]
    if isinstance(geometry, MultiLineString):
        return [part for part in geometry.geoms if not part.is_empty]
    if isinstance(geometry, GeometryCollection):
        lines: list[LineString] = []
        for part in geometry.geoms:
            lines.extend(_line_parts(part))
        return lines
    return []


def _nearest_source_line(
    segment: LineString,
    raw_lines: Sequence[AttributeDict],
    tree: STRtree,
    source_id_to_index: Mapping[int, int],
    snap_tolerance_m: float,
) -> AttributeDict | None:
    candidates = list(tree.query(segment))
    if not candidates:
        candidates = list(tree.query(segment.buffer(snap_tolerance_m)))
    best: tuple[float, AttributeDict] | None = None
    for candidate in candidates:
        index = int(candidate) if isinstance(candidate, Integral) else source_id_to_index[id(candidate)]
        raw_line = raw_lines[index]
        distance = segment.distance(raw_line["geometry"])
        if distance > snap_tolerance_m:
            continue
        overlap = segment.intersection(raw_line["geometry"]).length
        score = distance - overlap
        if best is None or score < best[0]:
            best = (score, raw_line)
    return best[1] if best else None


def _node_key(coord: tuple[float, float], precision_m: float) -> tuple[int, int]:
    return round(coord[0] / precision_m), round(coord[1] / precision_m)


def _ensure_node(
    graph: nx.DiGraph,
    node_ids_by_key: dict[tuple[int, int], str],
    key: tuple[int, int],
    coord: tuple[float, float],
    to_lonlat: Transformer,
    dem_transform: Any | None,
    dem_shape: tuple[int, int] | None,
) -> str:
    if key in node_ids_by_key:
        return node_ids_by_key[key]
    node_id = f"N{len(node_ids_by_key):06d}"
    lon, lat = to_lonlat.transform(coord[0], coord[1])
    node_attrs: AttributeDict = {
        "x": float(coord[0]),
        "y": float(coord[1]),
        "lon": float(lon),
        "lat": float(lat),
        "kind": "junction",
    }
    if dem_transform is not None:
        dem_index = snap_point_to_dem_grid(coord[0], coord[1], dem_transform, dem_shape)
        if dem_index is not None:
            node_attrs["dem_row"], node_attrs["dem_col"] = dem_index
    graph.add_node(node_id, **node_attrs)
    node_ids_by_key[key] = node_id
    return node_id


def _project_outfalls(
    outfall_points: Sequence[tuple[float, float]] | None, target_crs: str
) -> list[tuple[float, float]]:
    if not outfall_points:
        return []
    transformer = Transformer.from_crs(DEFAULT_SOURCE_CRS, target_crs, always_xy=True)
    projected = []
    for x, y in outfall_points:
        if abs(x) <= 180.0 and abs(y) <= 90.0:
            projected.append(transformer.transform(x, y))
        else:
            projected.append((x, y))
    return projected


def _direct_segment(
    *,
    segment: LineString,
    attributes: Mapping[str, Any],
    dem_sampler: DemSampler | None,
    outfall_points: Sequence[tuple[float, float]],
    direction_fallback: str,
) -> AttributeDict:
    coords = list(segment.coords)
    start = coords[0]
    end = coords[-1]
    start_elevation = _coord_z(start)
    end_elevation = _coord_z(end)
    method = "kml_coordinate_order"
    flow_hint = str(
        _lookup(attributes, ("flow_direction", "direction", "flow_dir", "FLOW_DIR")) or ""
    ).lower()

    if dem_sampler is not None:
        start_elevation = dem_sampler(start[0], start[1])
        end_elevation = dem_sampler(end[0], end[1])
        method = "dem_downhill"

    reverse = False
    if any(token in flow_hint for token in ("reverse", "backward")):
        reverse = True
        method = "kml_flow_direction"
    elif any(token in flow_hint for token in ("forward", "downstream", "coordinate")):
        method = "kml_flow_direction"
    elif start_elevation is not None and end_elevation is not None and abs(start_elevation - end_elevation) > 0.01:
        reverse = start_elevation < end_elevation
    elif outfall_points:
        reverse = _nearest_distance(start, outfall_points) < _nearest_distance(end, outfall_points)
        method = "nearest_outfall"
    elif direction_fallback:
        method = f"fallback_{direction_fallback}"
        reverse = _fallback_reverse(start, end, direction_fallback)

    if reverse:
        coords.reverse()
        start_elevation, end_elevation = end_elevation, start_elevation

    slope = None
    if start_elevation is not None and end_elevation is not None and segment.length > 0:
        slope = abs(start_elevation - end_elevation) / segment.length

    return {
        "coords": [(float(coord[0]), float(coord[1])) for coord in coords],
        "method": method,
        "start_elevation_m": start_elevation,
        "end_elevation_m": end_elevation,
        "inferred_slope": slope,
    }


def _edge_attributes(
    *,
    segment: LineString,
    source_attributes: Mapping[str, Any],
    hierarchy: str,
    direction: Mapping[str, Any],
    assumptions: Mapping[str, CapacityAssumption],
) -> AttributeDict:
    attrs: AttributeDict = {
        "geometry": segment,
        "length_m": float(segment.length),
        "hierarchy": hierarchy,
        "drain_type": _lookup(source_attributes, ("drain_type", "type", "Type", "TYPE")) or hierarchy,
        "ward": _lookup(source_attributes, ("ward", "Ward", "WARD", "ward_no", "Ward_No")),
        "name": _lookup(source_attributes, ("name", "Name", "NAME", "street", "Street")),
        "source_attributes": dict(source_attributes),
        "direction_method": direction["method"],
        "dem_start_elevation_m": direction["start_elevation_m"],
        "dem_end_elevation_m": direction["end_elevation_m"],
    }
    inferred_slope = direction.get("inferred_slope")
    if inferred_slope is not None and inferred_slope > 0:
        attrs["slope"] = inferred_slope
    capacity = estimate_capacity(attrs | dict(source_attributes), assumptions)
    attrs["capacity_m3s"] = capacity
    assumption = assumptions.get(hierarchy, assumptions["secondary"])
    attrs["capacity_assumption"] = asdict(assumption)
    attrs["manning_n"] = _positive_float(
        _parse_float(_lookup(source_attributes, ("manning_n", "n", "roughness"))),
        assumption.manning_n,
    )
    attrs["width_m"] = _positive_float(
        _parse_float(_lookup(source_attributes, ("width_m", "width", "drain_width", "top_width"))),
        assumption.width_m,
    )
    attrs["depth_m"] = _positive_float(
        _parse_float(_lookup(source_attributes, ("depth_m", "depth", "drain_depth", "height"))),
        assumption.depth_m,
    )
    attrs["slope"] = _positive_float(
        _parse_float(attrs.get("slope"))
        or _parse_float(_lookup(source_attributes, ("slope", "bed_slope", "gradient"))),
        assumption.slope,
    )
    return attrs


def _add_or_merge_edge(graph: nx.DiGraph, u: str, v: str, attrs: AttributeDict) -> None:
    if not graph.has_edge(u, v):
        attrs["segment_count"] = 1
        graph.add_edge(u, v, **attrs)
        return

    existing = graph.edges[u, v]
    existing["capacity_m3s"] += attrs["capacity_m3s"]
    existing["length_m"] += attrs["length_m"]
    existing["segment_count"] = existing.get("segment_count", 1) + 1
    existing.setdefault("merged_segments", []).append(attrs)


def _classify_node_kinds(graph: nx.DiGraph) -> None:
    for node_id in graph.nodes:
        in_degree = graph.in_degree(node_id)
        out_degree = graph.out_degree(node_id)
        total_degree = in_degree + out_degree
        if total_degree >= 3:
            kind = "junction"
        elif in_degree == 0 and out_degree > 0:
            kind = "inlet"
        elif out_degree == 0 and in_degree > 0:
            kind = "outfall"
        else:
            kind = "conduit_node"
        graph.nodes[node_id]["kind"] = kind


def _infer_hierarchy(attributes: Mapping[str, Any]) -> str:
    text = " ".join(
        str(value).lower()
        for key, value in attributes.items()
        if any(token in str(key).lower() for token in ("type", "hierarchy", "class", "category", "name"))
    )
    if any(token in text for token in ("macro", "primary", "trunk", "main", "major", "river", "canal")):
        return "primary"
    if any(token in text for token in ("tertiary", "minor", "local", "inlet")):
        return "tertiary"
    return "secondary"


def _diameter_metres(edge: Mapping[str, Any]) -> float | None:
    diameter_m = _parse_float(_lookup(edge, ("diameter_m", "dia_m", "pipe_diameter_m")))
    if diameter_m is not None and diameter_m > 0:
        return diameter_m
    diameter_mm = _parse_float(
        _lookup(edge, ("diameter_mm", "dia_mm", "size_of_pipe_mm", "pipe_diameter_mm"))
    )
    if diameter_mm is not None and diameter_mm > 0:
        return diameter_mm / 1000.0
    return None


def _lookup(attributes: Mapping[str, Any], names: Sequence[str]) -> Any | None:
    lower_lookup = {str(key).lower(): value for key, value in attributes.items()}
    for name in names:
        value = lower_lookup.get(name.lower())
        if value is not None and str(value) != "":
            return value
    return None


def _parse_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        digits = "".join(char if char.isdigit() or char in ".-" else " " for char in str(value))
        parts = [part for part in digits.split() if part]
        if not parts:
            return None
        try:
            return float(parts[0])
        except ValueError:
            return None


def _positive_float(value: float | None, fallback: float) -> float:
    return value if value is not None and value > 0 else fallback


def _coord_z(coord: Sequence[float]) -> float | None:
    return float(coord[2]) if len(coord) > 2 else None


def _nearest_distance(coord: Sequence[float], points: Sequence[tuple[float, float]]) -> float:
    return min(hypot(coord[0] - point[0], coord[1] - point[1]) for point in points)


def _fallback_reverse(start: Sequence[float], end: Sequence[float], direction_fallback: str) -> bool:
    fallback = direction_fallback.lower()
    if fallback == "east":
        return start[0] > end[0]
    if fallback == "west":
        return start[0] < end[0]
    if fallback == "north":
        return start[1] > end[1]
    if fallback == "south":
        return start[1] < end[1]
    return False


def _state_utilization(attrs: Mapping[str, Any]) -> float:
    state = attrs.get("state") or {}
    value = state.get("capacity_utilization", 0.0)
    if value == float("inf"):
        return 2.0
    return min(float(value), 2.0)


def _status_from_utilization(utilization: float) -> SurchargeStatus:
    if utilization >= 1.0:
        return SurchargeStatus.SURCHARGING
    if utilization >= 0.7:
        return SurchargeStatus.WATCH
    return SurchargeStatus.NORMAL
